name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Build the app
        run: ./scripts/buildprod.sh

      - name: Authenticate to GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: PROJECT_ID  # Replace with your GCP Project ID
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Build and push Docker image to Google Artifact Registry
        run: |
          gcloud builds submit --tag REGION-docker.pkg.dev/PROJECT_ID/notely-ar-repo/notely:latest .
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}